=== ComputerScienceHouse/bingehack/xml/dm-message.dtd
<!ELEMENT message (#PCDATA)>
<!ELEMENT buc (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT enchantment (#PCDATA)>
<!ELEMENT score (#PCDATA)>
<!ELEMENT epitaph (#PCDATA)>
<!ELEMENT turn (#PCDATA)>
<!ELEMENT dungeonLevel (#PCDATA)>
<!ELEMENT playerLevel (#PCDATA)>
<!ELEMENT hp (#PCDATA)>
<!ELEMENT hpMax (#PCDATA)>
<!ELEMENT class (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT levelType (#PCDATA)>
<!ELEMENT ac (#PCDATA)>
<!ELEMENT mp (#PCDATA)>
<!ELEMENT mpMax (#PCDATA)>
<!ELEMENT alignment (#PCDATA)>
<!ELEMENT race (#PCDATA)>

<!ELEMENT sender (name)>
<!ELEMENT receiver (name)>

<!ELEMENT chat (sender, receiver?, message)>
<!ELEMENT mail (sender, receiver, message, item?)>
<!ELEMENT item (buc, name, type, enchantment)>
<!ELEMENT playerData (
	turn,
	name,
	dungeonLevel?,
	playerLevel?,
	hp?,
	hpMax?,
	class?,
	gender?,
	levelType?,
	ac?,
	mp?,
	mpMax?,
	alignment?,
	race?
)>

<!ELEMENT inventory (item*)>

<!ELEMENT deathMessage (
	score,
	epitaph,
	playerData,
	inventory
)>

<!ELEMENT dm-message (deathMessage | playerData | mail | chat)>

=== ComputerScienceHouse/bingehack/xml/deathMessage.xml
<?xml version="1.0"?>
<!DOCTYPE dm-message SYSTEM "dm-message.dtd">
<dm-message>
	<deathMessage>
		<score>100</score>
		<epitaph>here lies russ, killed by a grue, while helpless</epitaph>
		<playerData>
			<turn>100</turn>
			<name>russ</name>
			<dungeonLevel>10</dungeonLevel>
			<playerLevel>5</playerLevel>
			<hp>100</hp>
			<hpMax>100</hpMax>
			<class>monk</class>
			<gender>male</gender>
			<levelType>Dungeons of Doom</levelType>
			<ac>5</ac>
			<mp>100</mp>
			<mpMax>100</mpMax>
			<alignment>chaotic</alignment>
			<race>human</race>
		</playerData>
		<inventory>
			<item>
				<buc>cursed</buc>
				<name></name>
				<type>silver dragon scale mail</type>
				<enchantment>-10</enchantment>
			</item>
			<item>
				<buc>blessed</buc>
				<name></name>
				<type>silver dragon scale mail</type>
				<enchantment>-10</enchantment>
			</item>
		</inventory>
	</deathMessage>
</dm-message>

=== ComputerScienceHouse/bingehack/xml/mail.xml
<?xml version="1.0"?>
<!DOCTYPE dm-message SYSTEM "dm-message.dtd">
<dm-message>
	<mail>
		<sender>
			<name>russ</name>
		</sender>
		<receiver>
			<name>devnull</name>
		</receiver>
		<message>Hello World!</message>
		<item>
			<buc>cursed</buc>
			<name></name>
			<type>silver dragon scale mail</type>
			<enchantment>-10</enchantment>
		</item>
	</mail>
</dm-message>
